version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_storage:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    command: server --console-address ":9001" /data


volumes:
  minio_storage: {}
  postgres_storage: {}

# docker-compose -f docker_compose.yml up

# pip3 install minio


# docker run \
#    -p 9000:9000 \
#    -p 9090:9090 \
#    --name minio1 \
#    -v D:\data \
#    -e "MINIO_ROOT_USER=ROOTUSER" \
#    -e "MINIO_ROOT_PASSWORD=CHANGEME123" \
#    quay.io/minio/minio server /data --console-address ":9090"